// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dhcp_client_dhcp_fsm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        dhcp_replyMetaFifo_V_dout,
        dhcp_replyMetaFifo_V_empty_n,
        dhcp_replyMetaFifo_V_read,
        portOpen_V_V_dout,
        portOpen_V_V_empty_n,
        portOpen_V_V_read,
        dhcp_requestMetaFifo_V_din,
        dhcp_requestMetaFifo_V_full_n,
        dhcp_requestMetaFifo_V_write,
        ipAddressOut_V,
        ipAddressOut_V_ap_vld,
        dhcpEnable_V,
        inputIpAddress_V
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_pp0_stg0_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv32_2CBF8C1E = 32'b101100101111111000110000011110;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_60 = 32'b1100000;
parameter    ap_const_lv32_67 = 32'b1100111;
parameter    ap_const_lv8_5 = 8'b101;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv8_2 = 8'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv8_3 = 8'b11;
parameter    ap_const_lv40_1 = 40'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [103:0] dhcp_replyMetaFifo_V_dout;
input   dhcp_replyMetaFifo_V_empty_n;
output   dhcp_replyMetaFifo_V_read;
input  [0:0] portOpen_V_V_dout;
input   portOpen_V_V_empty_n;
output   portOpen_V_V_read;
output  [71:0] dhcp_requestMetaFifo_V_din;
input   dhcp_requestMetaFifo_V_full_n;
output   dhcp_requestMetaFifo_V_write;
output  [31:0] ipAddressOut_V;
output   ipAddressOut_V_ap_vld;
input  [0:0] dhcpEnable_V;
input  [31:0] inputIpAddress_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg dhcp_replyMetaFifo_V_read;
reg portOpen_V_V_read;
reg[71:0] dhcp_requestMetaFifo_V_din;
reg dhcp_requestMetaFifo_V_write;
reg ipAddressOut_V_ap_vld;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm = 1'b1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_0;
reg    ap_sig_bdd_20;
wire    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [2:0] state_load_load_fu_278_p1;
wire   [0:0] grp_nbreadreq_fu_138_p3;
wire   [0:0] tmp_nbreadreq_fu_152_p3;
reg    ap_sig_bdd_76;
reg   [2:0] state_load_reg_432;
reg   [0:0] tmp_5_reg_469;
reg   [0:0] tmp_9_reg_482;
reg   [0:0] tmp_11_reg_486;
reg   [0:0] dhcpEnable_V_read_reg_436;
reg   [0:0] tmp_s_reg_490;
reg    ap_sig_bdd_110;
reg   [31:0] myIpAddress_V = 32'b00000000000000000000000000000000;
reg   [2:0] state = 3'b000;
reg   [31:0] time_V = 32'b1100100;
reg   [31:0] randomValue_V = 32'b110100101010101101001101001011;
reg   [31:0] myIdentity_V = 32'b00000000000000000000000000000000;
reg   [31:0] IpAddressBuffer_V = 32'b00000000000000000000000000000000;
wire   [0:0] dhcpEnable_V_read_read_fu_132_p2;
reg   [31:0] tmp_identifier_V_reg_440;
reg   [31:0] myIdentity_V_load_reg_445;
wire   [0:0] tmp_4_fu_230_p2;
wire   [0:0] tmp_2_fu_312_p2;
wire   [0:0] grp_fu_235_p2;
reg   [31:0] tmp_requestedIpAddress_V_reg_477;
wire   [0:0] tmp_9_fu_350_p2;
wire   [0:0] tmp_11_fu_356_p2;
wire   [2:0] ap_reg_phiprechg_storemerge_reg_180pp0_it0;
wire   [0:0] tmp_13_fu_318_p2;
reg   [2:0] storemerge_phi_fu_183_p4;
wire   [1:0] ap_reg_phiprechg_storemerge1_reg_191pp0_it0;
reg   [1:0] storemerge1_phi_fu_194_p4;
wire   [31:0] ap_reg_phiprechg_t_V_1_reg_202pp0_it0;
reg   [31:0] t_V_1_phi_fu_205_p16;
wire   [31:0] p_s_fu_390_p2;
wire   [71:0] tmp_2_2_fu_415_p4;
wire   [71:0] tmp22_fu_424_p3;
wire   [2:0] storemerge1_cast_fu_368_p1;
wire   [31:0] grp_fu_240_p2;
wire   [31:0] tmp_15_fu_403_p2;
wire   [31:0] tmp_19_fu_308_p1;
wire   [7:0] grp_fu_251_p4;
wire   [31:0] tmp_identifier_V_1_fu_336_p1;
wire   [31:0] tmp_20_fu_384_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_pprstidle_pp0;
reg    ap_sig_bdd_97;
reg    ap_sig_bdd_108;
reg    ap_sig_bdd_261;
reg    ap_sig_bdd_408;
reg    ap_sig_bdd_410;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (state_load_load_fu_278_p1 == ap_const_lv3_1)))) begin
        myIpAddress_V <= inputIpAddress_V;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_2_fu_312_p2) & ~(ap_const_lv1_0 == tmp_13_fu_318_p2))) begin
        myIpAddress_V <= IpAddressBuffer_V;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2) & ~(ap_const_lv1_0 == grp_fu_235_p2))) begin
        state <= ap_const_lv3_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_9_fu_350_p2))) begin
        state <= storemerge1_cast_fu_368_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_2_fu_312_p2))) begin
        state <= storemerge_phi_fu_183_p4;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_0) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_152_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_4) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_4_fu_230_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == grp_fu_235_p2)))) begin
        state <= ap_const_lv3_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_9_fu_350_p2) & ~(ap_const_lv1_0 == tmp_11_fu_356_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2) & ~(ap_const_lv1_0 == grp_fu_235_p2)))) begin
        time_V <= ap_const_lv32_2CBF8C1E;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2) & (ap_const_lv1_0 == grp_fu_235_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv1_0 == tmp_4_fu_230_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (ap_const_lv1_0 == grp_fu_235_p2)))) begin
        time_V <= grp_fu_240_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_9_fu_350_p2) & ~(ap_const_lv1_0 == tmp_11_fu_356_p2))) begin
        IpAddressBuffer_V <= {{dhcp_replyMetaFifo_V_dout[ap_const_lv32_3F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        dhcpEnable_V_read_reg_436 <= dhcpEnable_V;
        myIdentity_V_load_reg_445 <= myIdentity_V;
        state_load_reg_432 <= state;
        tmp_identifier_V_reg_440 <= randomValue_V;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2) & ~(ap_const_lv1_0 == grp_fu_235_p2))) begin
        myIdentity_V <= randomValue_V;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        randomValue_V <= tmp_15_fu_403_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(ap_const_lv1_0 == tmp_9_fu_350_p2))) begin
        tmp_11_reg_486 <= tmp_11_fu_356_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        tmp_5_reg_469 <= grp_nbreadreq_fu_138_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        tmp_9_reg_482 <= tmp_9_fu_350_p2;
        tmp_requestedIpAddress_V_reg_477 <= {{dhcp_replyMetaFifo_V_dout[ap_const_lv32_3F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2))) begin
        tmp_s_reg_490 <= grp_fu_235_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_76 or ap_sig_bdd_110)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it1))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_76 or ap_sig_bdd_110)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_0 assign process. ///
always @ (ap_sig_bdd_20)
begin
    if (ap_sig_bdd_20) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_pprstidle_pp0 assign process. ///
always @ (ap_start or ap_reg_ppiten_pp0_it0)
begin
    if (((ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_start))) begin
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    end else begin
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    end
end

/// dhcp_replyMetaFifo_V_read assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or grp_nbreadreq_fu_138_p3 or ap_sig_bdd_76 or ap_sig_bdd_110 or state)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_4) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        dhcp_replyMetaFifo_V_read = ap_const_logic_1;
    end else begin
        dhcp_replyMetaFifo_V_read = ap_const_logic_0;
    end
end

/// dhcp_requestMetaFifo_V_din assign process. ///
always @ (tmp_2_2_fu_415_p4 or tmp22_fu_424_p3 or ap_sig_bdd_97 or ap_sig_bdd_108 or ap_sig_bdd_261)
begin
    if (ap_sig_bdd_261) begin
        if (ap_sig_bdd_108) begin
            dhcp_requestMetaFifo_V_din = tmp22_fu_424_p3;
        end else if (ap_sig_bdd_97) begin
            dhcp_requestMetaFifo_V_din = tmp_2_2_fu_415_p4;
        end else begin
            dhcp_requestMetaFifo_V_din = 'bx;
        end
    end else begin
        dhcp_requestMetaFifo_V_din = 'bx;
    end
end

/// dhcp_requestMetaFifo_V_write assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_76 or state_load_reg_432 or tmp_5_reg_469 or tmp_9_reg_482 or tmp_11_reg_486 or dhcpEnable_V_read_reg_436 or tmp_s_reg_490 or ap_sig_bdd_110)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_lv3_2 == state_load_reg_432) & ~(ap_const_lv1_0 == tmp_5_reg_469) & ~(ap_const_lv1_0 == tmp_9_reg_482) & ~(ap_const_lv1_0 == tmp_11_reg_486) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (state_load_reg_432 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_reg_436) & ~(ap_const_lv1_0 == tmp_s_reg_490) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))))) begin
        dhcp_requestMetaFifo_V_write = ap_const_logic_1;
    end else begin
        dhcp_requestMetaFifo_V_write = ap_const_logic_0;
    end
end

/// ipAddressOut_V_ap_vld assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_76 or ap_sig_bdd_110)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        ipAddressOut_V_ap_vld = ap_const_logic_1;
    end else begin
        ipAddressOut_V_ap_vld = ap_const_logic_0;
    end
end

/// portOpen_V_V_read assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or tmp_nbreadreq_fu_152_p3 or ap_sig_bdd_76 or ap_sig_bdd_110 or state)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_0) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_152_p3) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        portOpen_V_V_read = ap_const_logic_1;
    end else begin
        portOpen_V_V_read = ap_const_logic_0;
    end
end

/// storemerge1_phi_fu_194_p4 assign process. ///
always @ (tmp_11_fu_356_p2 or ap_reg_phiprechg_storemerge1_reg_191pp0_it0 or ap_sig_bdd_408)
begin
    if (ap_sig_bdd_408) begin
        if ((ap_const_lv1_0 == tmp_11_fu_356_p2)) begin
            storemerge1_phi_fu_194_p4 = ap_const_lv2_1;
        end else if (~(ap_const_lv1_0 == tmp_11_fu_356_p2)) begin
            storemerge1_phi_fu_194_p4 = ap_const_lv2_3;
        end else begin
            storemerge1_phi_fu_194_p4 = ap_reg_phiprechg_storemerge1_reg_191pp0_it0;
        end
    end else begin
        storemerge1_phi_fu_194_p4 = ap_reg_phiprechg_storemerge1_reg_191pp0_it0;
    end
end

/// storemerge_phi_fu_183_p4 assign process. ///
always @ (ap_reg_phiprechg_storemerge_reg_180pp0_it0 or tmp_13_fu_318_p2 or ap_sig_bdd_410)
begin
    if (ap_sig_bdd_410) begin
        if ((ap_const_lv1_0 == tmp_13_fu_318_p2)) begin
            storemerge_phi_fu_183_p4 = ap_const_lv3_1;
        end else if (~(ap_const_lv1_0 == tmp_13_fu_318_p2)) begin
            storemerge_phi_fu_183_p4 = ap_const_lv3_4;
        end else begin
            storemerge_phi_fu_183_p4 = ap_reg_phiprechg_storemerge_reg_180pp0_it0;
        end
    end else begin
        storemerge_phi_fu_183_p4 = ap_reg_phiprechg_storemerge_reg_180pp0_it0;
    end
end

/// t_V_1_phi_fu_205_p16 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or state_load_load_fu_278_p1 or state or randomValue_V or dhcpEnable_V_read_read_fu_132_p2 or grp_fu_235_p2 or ap_reg_phiprechg_t_V_1_reg_202pp0_it0 or p_s_fu_390_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2) & ~(ap_const_lv1_0 == grp_fu_235_p2))) begin
        t_V_1_phi_fu_205_p16 = p_s_fu_390_p2;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(state == ap_const_lv3_4) & ~(state == ap_const_lv3_3) & ~(state == ap_const_lv3_2) & ~(state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(state == ap_const_lv3_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & (ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state_load_load_fu_278_p1 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_read_fu_132_p2) & (ap_const_lv1_0 == grp_fu_235_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (state == ap_const_lv3_0)))) begin
        t_V_1_phi_fu_205_p16 = randomValue_V;
    end else begin
        t_V_1_phi_fu_205_p16 = ap_reg_phiprechg_t_V_1_reg_202pp0_it0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_done_reg or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_76 or ap_sig_bdd_110 or ap_sig_pprstidle_pp0)
begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_storemerge1_reg_191pp0_it0 = 'bx;
assign ap_reg_phiprechg_storemerge_reg_180pp0_it0 = 'bx;
assign ap_reg_phiprechg_t_V_1_reg_202pp0_it0 = 'bx;
assign ap_reg_ppiten_pp0_it0 = ap_start;

/// ap_sig_bdd_108 assign process. ///
always @ (state_load_reg_432 or dhcpEnable_V_read_reg_436 or tmp_s_reg_490)
begin
    ap_sig_bdd_108 = ((state_load_reg_432 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_reg_436) & ~(ap_const_lv1_0 == tmp_s_reg_490));
end

/// ap_sig_bdd_110 assign process. ///
always @ (dhcp_requestMetaFifo_V_full_n or state_load_reg_432 or tmp_5_reg_469 or tmp_9_reg_482 or tmp_11_reg_486 or dhcpEnable_V_read_reg_436 or tmp_s_reg_490)
begin
    ap_sig_bdd_110 = (((dhcp_requestMetaFifo_V_full_n == ap_const_logic_0) & (ap_const_lv3_2 == state_load_reg_432) & ~(ap_const_lv1_0 == tmp_5_reg_469) & ~(ap_const_lv1_0 == tmp_9_reg_482) & ~(ap_const_lv1_0 == tmp_11_reg_486)) | ((dhcp_requestMetaFifo_V_full_n == ap_const_logic_0) & (state_load_reg_432 == ap_const_lv3_1) & ~(ap_const_lv1_0 == dhcpEnable_V_read_reg_436) & ~(ap_const_lv1_0 == tmp_s_reg_490)));
end

/// ap_sig_bdd_20 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_20 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_261 assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_76 or ap_sig_bdd_110)
begin
    ap_sig_bdd_261 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_done_reg == ap_const_logic_1) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_76) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))));
end

/// ap_sig_bdd_408 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or grp_nbreadreq_fu_138_p3 or state or tmp_9_fu_350_p2)
begin
    ap_sig_bdd_408 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2) & ~(ap_const_lv1_0 == tmp_9_fu_350_p2));
end

/// ap_sig_bdd_410 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or grp_nbreadreq_fu_138_p3 or state or tmp_2_fu_312_p2)
begin
    ap_sig_bdd_410 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3) & ~(ap_const_lv1_0 == tmp_2_fu_312_p2));
end

/// ap_sig_bdd_76 assign process. ///
always @ (ap_start or ap_done_reg or dhcp_replyMetaFifo_V_empty_n or grp_nbreadreq_fu_138_p3 or portOpen_V_V_empty_n or tmp_nbreadreq_fu_152_p3 or state)
begin
    ap_sig_bdd_76 = (((dhcp_replyMetaFifo_V_empty_n == ap_const_logic_0) & (state == ap_const_lv3_4) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0)) | ((dhcp_replyMetaFifo_V_empty_n == ap_const_logic_0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_3)) | ((dhcp_replyMetaFifo_V_empty_n == ap_const_logic_0) & ~(grp_nbreadreq_fu_138_p3 == ap_const_lv1_0) & (state == ap_const_lv3_2)) | ((portOpen_V_V_empty_n == ap_const_logic_0) & (state == ap_const_lv3_0) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_152_p3)) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_97 assign process. ///
always @ (state_load_reg_432 or tmp_5_reg_469 or tmp_9_reg_482 or tmp_11_reg_486)
begin
    ap_sig_bdd_97 = ((ap_const_lv3_2 == state_load_reg_432) & ~(ap_const_lv1_0 == tmp_5_reg_469) & ~(ap_const_lv1_0 == tmp_9_reg_482) & ~(ap_const_lv1_0 == tmp_11_reg_486));
end
assign dhcpEnable_V_read_read_fu_132_p2 = dhcpEnable_V;
assign grp_fu_235_p2 = (time_V == ap_const_lv32_0? 1'b1: 1'b0);
assign grp_fu_240_p2 = ($signed(time_V) + $signed(ap_const_lv32_FFFFFFFF));
assign grp_fu_251_p4 = {{dhcp_replyMetaFifo_V_dout[ap_const_lv32_67 : ap_const_lv32_60]}};
assign grp_nbreadreq_fu_138_p3 = dhcp_replyMetaFifo_V_empty_n;
assign ipAddressOut_V = myIpAddress_V;
assign p_s_fu_390_p2 = (randomValue_V ^ tmp_20_fu_384_p2);
assign state_load_load_fu_278_p1 = state;
assign storemerge1_cast_fu_368_p1 = storemerge1_phi_fu_194_p4;
assign tmp22_fu_424_p3 = {{ap_const_lv40_1}, {tmp_identifier_V_reg_440}};
assign tmp_11_fu_356_p2 = (grp_fu_251_p4 == ap_const_lv8_2? 1'b1: 1'b0);
assign tmp_13_fu_318_p2 = (grp_fu_251_p4 == ap_const_lv8_5? 1'b1: 1'b0);
assign tmp_15_fu_403_p2 = (t_V_1_phi_fu_205_p16 + ap_const_lv32_1);
assign tmp_19_fu_308_p1 = dhcp_replyMetaFifo_V_dout[31:0];
assign tmp_20_fu_384_p2 = randomValue_V << ap_const_lv32_3;
assign tmp_2_2_fu_415_p4 = {{{tmp_requestedIpAddress_V_reg_477}, {ap_const_lv8_3}}, {myIdentity_V_load_reg_445}};
assign tmp_2_fu_312_p2 = (tmp_19_fu_308_p1 == myIdentity_V? 1'b1: 1'b0);
assign tmp_4_fu_230_p2 = (time_V == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_9_fu_350_p2 = (tmp_identifier_V_1_fu_336_p1 == myIdentity_V? 1'b1: 1'b0);
assign tmp_identifier_V_1_fu_336_p1 = dhcp_replyMetaFifo_V_dout[31:0];
assign tmp_nbreadreq_fu_152_p3 = portOpen_V_V_empty_n;


endmodule //dhcp_client_dhcp_fsm

